name: SDK Generation CI

on:
  workflow_run:
    workflows: [ "Release CI" ]
    types:
    - completed

jobs:
  generate-go-sdk:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout apis repository
      uses: actions/checkout@v4
    - name: Get current tag
      id: fetch_tag
      run: |
        current_tag=$(git tag --points-at HEAD)
        if [[ -z $current_tag ]]; then
          exit(1)
        fi
        echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
      continue-on-error: false
    - name: Set up Buf
      uses: bufbuild/buf-action@v1
      with:
        token: ${{ secrets.BUF_TOKEN }}
    - name: Checkout gengo repository
      uses: actions/checkout@v4
      with:
        repository: vinea-dev/gengo
        path: gen/go
        ssh-key: ${{ secrets.SDK_GENERATOR_KEY }}
    - name: Cleanup the target directory
      run: |
        find gen/go -type f -regex '.*\(.go\|.py\|.pyc\|.pyi\|.java\|.html\)$' -delete
        find gen/go -type d -empty -delete
    - name: Generate Go SDK
      run: buf generate
    - name: Commit and push changes
      run: |
        cd gen/go
        go mod tidy
        git config --global user.name "Github Action Bot"
        git config --global user.email "vinea-dev@users.noreply.github.com"
        if [[ -n "$(git status --porcelain)" ]]; then
          git add .
          git commit -m "feat(sdk): regenerate sdk from apis commit ${{ github.sha }}"
          git tag ${{steps.fetch_tag.outputs.current_tag}}
          git push -f origin main --tags
        else
          echo "No changes to commit"
        fi
      working-directory: ${{ github.workspace }}
